name: Continous integration for sauerbraten
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            use-xcode: true
            working-directory: ./src/xcode
          - os: windows-latest
            use-msbuild: true
            working-directory: ./src/vcpp
          - os: ubuntu-latest
            install-headerfiles: true
            working-directory: ./src
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      if: matrix.use-msbuild
    - name: Install C and C++ header files
      run: sudo apt-get install -y libsdl-dev libsdl2-mixer-dev libsdl2-image-dev zlib1g-dev
      if: matrix.install-headerfiles
    - name: Build for OSX
      working-directory: ${{ matrix.working-directory }}
      run: xcodebuild
      if: matrix.use-xcode
    - name: Build for Windows
      working-directory: ${{ matrix.working-directory }}
      run: msbuild /p:PlatformToolset=v142 sauerbraten.sln
      if: matrix.use-msbuild
    - name: Build for Ubuntu
      working-directory: ${{ matrix.working-directory }}
      run: make
      if: matrix.install-headerfiles
