name: Continous integration for Tomatenquark
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build for OSX
        working-directory: ./src/xcode
        run: xcodebuild
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache vcpkg's artifacts
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/vcpkg/
          # The key will be different each time a different version of vcpkg is used, or different ports are installed.
          key: ${{ hashFiles( src/vcpp/vcpkg_x64-windows.txt ) }}-${{ hashFiles('.git/modules/vcpkg/HEAD') }}-${{ runner.os }}
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v0
        with:
        # Response file stored in source control, it provides the list of ports and triplet(s).
          vcpkgArguments: src/vcpp/vcpkg_x64-windows.txt
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build for Windows
        working-directory: ./src/vcpp
        run: msbuild /property:Platform=x64 tomatenquark.sln
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install C and C++ header files
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl-dev libsdl2-mixer-dev libsdl2-image-dev zlib1g-dev
      - name: Build for Ubuntu
        working-directory: ./src
        run: make
