name: Continous integration for Tomatenquark
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build for OSX
        working-directory: ./src/xcode
        run: xcodebuild
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build for Windows
        working-directory: ./src/vcpp
        run: msbuild /p:PlatformToolset=v142 /property:Platform=x64 tomatenquark.sln
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      vcpkgResponseFile: cmake/triplets/linux-ci
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v3
        with:
          vcpkgArguments: zlib enet sdl2 sdl2-image sdl2-mixer --triplet x64-linux
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: afc18d71004a507de5de303f163a1f83f001e03a
          appendedCacheKey: afc18d71004a507de5de303f163a1f83f001e03a
      - name: Build for Ubuntu
        run: mkdir build && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake && make
