name: Continous integration for sauerbraten
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install conan && conan package tools
        run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install conan_package_tools
      - name: Build for OSX
        working-directory: ./src/xcode
        run: |
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
          conan install . --build=missing
          xcodebuild
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build for Windows
        working-directory: ./src/vcpp
        run: msbuild /p:PlatformToolset=v142 /property:Platform=x64 sauerbraten.sln
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install conan && conan package tools
        run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install conan_package_tools
      - name: Build for Ubuntu
        working-directory: ./src
        run: |
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan install . --build=missing
          make
